default_language_version:
    python: python3.11

repos:
  # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.12.1
    hooks:
      - id: black
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.13
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  -   repo: https://github.com/awslabs/cfn-python-lint
      rev: v0.84.0
      hooks:
      -   id: cfn-python-lint
          files: .*(cfn|cloudformation).*\.(json|yml|yaml)$
